server:
  port: 8764

spring:
  application:
    name: permission
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.99.100:3306/seng_permission?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 192.168.99.100
    port: 6379
    password:
    lettuce:
      pool:
        max-wait: 1
        max-active: 200
        max-idle: 10
        min-idle: 0
    timeout: 1000


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.xy.permission.pojo
  # config-location: classpath:mybatis-config.xml

logging:
  level:
    com:
      example:
        mapper : debug


